name: Django CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
          MYSQL_ROOT_PASSWORD: root_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r messaging_app/requirements.txt

      - name: Install code quality tools
        run: pip install flake8 coverage

      - name: Run flake8 lint
        run: flake8 messaging_app/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run full flake8 check
        run: flake8 messaging_app/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        run: coverage run -m pytest messaging_app/messaging_app/tests/ --junitxml=report.xml

      - name: Generate coverage report
        run: coverage xml -o coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
