version: '3.8'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=messaging_app.settings
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_USER=messaginguser
      - MYSQL_DB=messagingdb
      - MYSQL_PASSWORD=userpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=messagingdb
    ports:
      - "3306:3306"
    restart: always

volumes:
  mysql_data: